# Generated by Django 5.2.17 on 2026-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "course_interested",
                    models.CharField(default="JEE Main & Advanced", max_length=200),
                ),
                ("current_class", models.CharField(default="Class 11", max_length=50)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New Inquiry"),
                            ("CONTACTED", "Counselor Contacted"),
                            ("CONVERTED", "Enrolled"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CAMPUS", "Modern Campus & Classrooms"),
                            ("LABS", "Advanced Science & Computer Labs"),
                            ("AWARDS", "Felicitation & Award Ceremonies"),
                            ("EVENTS", "Seminars & Doubt Clearing Workshops"),
                        ],
                        default="CAMPUS",
                        max_length=50,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("URGENT", "Urgent Announcement"),
                            ("EXAM", "Exam & Test Schedule"),
                            ("HOLIDAY", "Holiday Notice"),
                            ("EVENT", "Workshop & Special Seminar"),
                            ("GENERAL", "General Update"),
                        ],
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("ALL", "All Users & Public"),
                            ("STUDENT", "Students Only"),
                            ("TEACHER", "Faculty Only"),
                        ],
                        default="ALL",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("published_date", models.DateField(auto_now_add=True)),
                (
                    "attachment_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-published_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("student_name", models.CharField(max_length=150)),
                ("exam_name", models.CharField(default="JEE Advanced", max_length=150)),
                ("rank_or_score", models.CharField(default="AIR 48", max_length=100)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("summary", models.CharField(max_length=300)),
                ("story", models.TextField()),
                ("year", models.IntegerField(default=2025)),
                ("is_featured", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-year", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("student_name", models.CharField(max_length=150)),
                (
                    "course_name",
                    models.CharField(
                        default="JEE Advanced 2-Year Classroom", max_length=150
                    ),
                ),
                (
                    "score_or_rank",
                    models.CharField(default="AIR 142 (JEE Advanced)", max_length=100),
                ),
                (
                    "college_admitted",
                    models.CharField(
                        default="IIT Bombay (Computer Science)", max_length=200
                    ),
                ),
                ("review_text", models.TextField()),
                ("rating", models.IntegerField(default=5)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("year", models.IntegerField(default=2025)),
                ("is_featured", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-year", "-rating"],
            },
        ),
    ]
