# Generated by Django 5.2.17 on 2026-08-26 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("PDF_NOTES", "Comprehensive Lecture Notes"),
                            ("FORMULA_SHEET", "Quick Revision Formula Sheet"),
                            ("DPP", "Daily Practice Problems (DPP)"),
                            ("PYQ", "Previous Year Question Bank"),
                            ("ASSIGNMENT", "Class Assignment / Homework"),
                        ],
                        default="PDF_NOTES",
                        max_length=50,
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="URL to PDF or cloud storage document", max_length=500
                    ),
                ),
                (
                    "file_size_mb",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
                ),
                ("download_count", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academic.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academic.course",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "video_url",
                    models.URLField(
                        help_text="Direct MP4 URL, YouTube Embed, or Vimeo URL",
                        max_length=500,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=45, help_text="Duration in minutes"),
                ),
                ("order", models.IntegerField(default=1)),
                ("is_published", models.BooleanField(default=True)),
                ("is_free_preview", models.BooleanField(default=False)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="academic.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_lessons",
                        to="academic.course",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_lessons",
                        to="academic.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("watched_duration_seconds", models.IntegerField(default=0)),
                ("last_position_seconds", models.IntegerField(default=0)),
                ("last_watched_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="lms.videolesson",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "video")},
            },
        ),
    ]
