# Generated by Django 5.2.17 on 2026-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "schedule_time",
                    models.CharField(
                        default="Mon, Wed, Fri (4:00 PM - 7:30 PM)", max_length=150
                    ),
                ),
                (
                    "classroom",
                    models.CharField(default="Lecture Hall Alpha-1", max_length=100),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("OFFLINE", "Offline Classroom"),
                            ("ONLINE", "Live Interactive"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="HYBRID",
                        max_length=50,
                    ),
                ),
                ("max_capacity", models.IntegerField(default=40)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BatchEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("chapter_number", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=1, default=8.0, max_digits=4),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "chapter_number"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ENGINEERING", "Engineering (JEE Main & Advanced)"),
                            ("MEDICAL", "Medical (NEET-UG)"),
                            ("FOUNDATION", "Foundation & Olympiad (Class 8-10)"),
                            ("BOARDS", "Target Board Excellence (Class 11-12)"),
                            ("CRASH_COURSE", "Fast-Track Crash Course & Test Series"),
                        ],
                        default="ENGINEERING",
                        max_length=50,
                    ),
                ),
                ("short_description", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "target_class",
                    models.CharField(default="Class 11 & 12", max_length=50),
                ),
                ("duration_weeks", models.IntegerField(default=52)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=45000.0, max_digits=10
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key bullet highlights",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-is_featured", "title"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("icon", models.CharField(default="book-open", max_length=100)),
                ("color_accent", models.CharField(default="#3B82F6", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
