# Generated by Django 5.2.17 on 2026-08-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="badge_text",
            field=models.CharField(
                blank=True,
                help_text="e.g. MOST POPULAR, IIT FOCUSED, FOUNDATION",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="faqs",
            field=models.JSONField(
                blank=True, default=list, help_text="List of {question, answer} dicts"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="mode",
            field=models.CharField(
                default="Offline Classroom & Live Hybrid", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="overview_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured overview, pedagogy, and target eligibility",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOUNDATION", "Foundation Programs (Classes 6-10)"),
                    ("ENGINEERING", "JEE Preparation (Main & Advanced)"),
                    ("MEDICAL", "NEET Preparation (Medical Entrance)"),
                    ("OTHER_EXAMS", "Other Competitive Exams (CUET, NDA, Olympiads)"),
                    ("BOARDS", "Target Board Excellence (Class 11-12)"),
                    ("CRASH_COURSE", "Fast-Track Crash Course & Test Series"),
                ],
                default="ENGINEERING",
                max_length=50,
            ),
        ),
    ]
